services:
  - type: web
    name: yt-dlp-api
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DOWNLOAD_DIR
        value: "/tmp/downloads"
    disk:
      name: downloads
      mountPath: /tmp/downloads
      sizeGB: 1